# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkdb.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from dbserver.classmanager import ClassManager
from dbserver.avtomanager import AvtoManager
from dbserver.charmanager import CharManager
from dbserver.avtocharmanager import AvtoCharManager
from dbserver.dbworker import DBWorker


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(40, 390, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 461, 361))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Проверка целосности "))
        self.backBtn.setText(_translate("MainWindow", "Назад"))

class CheckWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        dbw = DBWorker()
        logs = '' + ClassManager(dbw).getlogs() + CharManager(dbw).getlogs() + AvtoManager(dbw).getlogs() + AvtoCharManager(dbw).getlogs()
        self.textBrowser.setText(logs)
        self.backBtn.clicked.connect(self.returnM)

    def returnM(self):
        self.close()
        if self.parent():
            self.parent().show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainwin = CheckWindow()
    mainwin.show()
    sys.exit(app.exec_())
